# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json
PackageIdentifier: cccadet.omni-sql
PackageVersion: 0.5.4
InstallerType: nullsoft
Scope: user
UpgradeBehavior: install
ProductCode: omni-sql
AppsAndFeaturesEntries:
  - DisplayName: omni-sql
    DisplayVersion: 0.5.4
    Publisher: omnisql
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/cccadet/omni-sql/releases/download/v0.5.4/omni-sql_0.5.4_x64-setup.exe
    InstallerSha256: 3F88BB1D8C559697C14D13164CFE32C977A2468B0DA5F34B08DB34DF3CA471D1
ManifestType: installer
ManifestVersion: 1.10.0
